// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDoneCloser creates a new instance of MockDoneCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoneCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoneCloser {
	mock := &MockDoneCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoneCloser is an autogenerated mock type for the DoneCloser type
type MockDoneCloser struct {
	mock.Mock
}

type MockDoneCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoneCloser) EXPECT() *MockDoneCloser_Expecter {
	return &MockDoneCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDoneCloser
func (_mock *MockDoneCloser) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDoneCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDoneCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDoneCloser_Expecter) Close() *MockDoneCloser_Close_Call {
	return &MockDoneCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDoneCloser_Close_Call) Run(run func()) *MockDoneCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDoneCloser_Close_Call) Return(err error) *MockDoneCloser_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDoneCloser_Close_Call) RunAndReturn(run func() error) *MockDoneCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockDoneCloser
func (_mock *MockDoneCloser) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockDoneCloser_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockDoneCloser_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockDoneCloser_Expecter) Done() *MockDoneCloser_Done_Call {
	return &MockDoneCloser_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockDoneCloser_Done_Call) Run(run func()) *MockDoneCloser_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDoneCloser_Done_Call) Return(valCh <-chan struct{}) *MockDoneCloser_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockDoneCloser_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockDoneCloser_Done_Call {
	_c.Call.Return(run)
	return _c
}
