//
// Copyright 2025 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: pkg/apis/vmagent/v1alpha1/vmagent.proto

package vmagentv1alpha1

import (
	_ "github.com/alexandremahdhaoui/udplb/pkg/apis/common/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_apis_vmagent_v1alpha1_vmagent_proto protoreflect.FileDescriptor

const file_pkg_apis_vmagent_v1alpha1_vmagent_proto_rawDesc = "" +
	"\n" +
	"'pkg/apis/vmagent/v1alpha1/vmagent.proto\x12\x0fvmagentv1alpha1\x1a%pkg/apis/common/v1alpha1/common.protoBOZMgithub.com/alexandremahdhaoui/udplb/pkg/apis/vmagent/v1alpha1;vmagentv1alpha1b\x06proto3"

var file_pkg_apis_vmagent_v1alpha1_vmagent_proto_goTypes = []any{}
var file_pkg_apis_vmagent_v1alpha1_vmagent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_apis_vmagent_v1alpha1_vmagent_proto_init() }
func file_pkg_apis_vmagent_v1alpha1_vmagent_proto_init() {
	if File_pkg_apis_vmagent_v1alpha1_vmagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_vmagent_v1alpha1_vmagent_proto_rawDesc), len(file_pkg_apis_vmagent_v1alpha1_vmagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_apis_vmagent_v1alpha1_vmagent_proto_goTypes,
		DependencyIndexes: file_pkg_apis_vmagent_v1alpha1_vmagent_proto_depIdxs,
	}.Build()
	File_pkg_apis_vmagent_v1alpha1_vmagent_proto = out.File
	file_pkg_apis_vmagent_v1alpha1_vmagent_proto_goTypes = nil
	file_pkg_apis_vmagent_v1alpha1_vmagent_proto_depIdxs = nil
}
