// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpfadapter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type udplbBackendSpec struct {
	Ip      uint32
	Port    uint16
	Mac     [6]uint8
	Enabled bool
	_       [3]byte
}

type udplbConfigT struct {
	Ip   uint32
	Port uint16
	_    [2]byte
}

// loadUdplb returns the embedded CollectionSpec for udplb.
func loadUdplb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UdplbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load udplb: %w", err)
	}

	return spec, err
}

// loadUdplbObjects loads udplb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*udplbObjects
//	*udplbPrograms
//	*udplbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUdplbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUdplb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// udplbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udplbSpecs struct {
	udplbProgramSpecs
	udplbMapSpecs
	udplbVariableSpecs
}

// udplbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udplbProgramSpecs struct {
	Udplb *ebpf.ProgramSpec `ebpf:"udplb"`
}

// udplbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udplbMapSpecs struct {
	Backends *ebpf.MapSpec `ebpf:"backends"`
}

// udplbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udplbVariableSpecs struct {
	Config     *ebpf.VariableSpec `ebpf:"config"`
	N_backends *ebpf.VariableSpec `ebpf:"n_backends"`
}

// udplbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUdplbObjects or ebpf.CollectionSpec.LoadAndAssign.
type udplbObjects struct {
	udplbPrograms
	udplbMaps
	udplbVariables
}

func (o *udplbObjects) Close() error {
	return _UdplbClose(
		&o.udplbPrograms,
		&o.udplbMaps,
	)
}

// udplbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUdplbObjects or ebpf.CollectionSpec.LoadAndAssign.
type udplbMaps struct {
	Backends *ebpf.Map `ebpf:"backends"`
}

func (m *udplbMaps) Close() error {
	return _UdplbClose(
		m.Backends,
	)
}

// udplbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUdplbObjects or ebpf.CollectionSpec.LoadAndAssign.
type udplbVariables struct {
	Config     *ebpf.Variable `ebpf:"config"`
	N_backends *ebpf.Variable `ebpf:"n_backends"`
}

// udplbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUdplbObjects or ebpf.CollectionSpec.LoadAndAssign.
type udplbPrograms struct {
	Udplb *ebpf.Program `ebpf:"udplb"`
}

func (p *udplbPrograms) Close() error {
	return _UdplbClose(
		p.Udplb,
	)
}

func _UdplbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed zz_generated_bpfeb.o
var _UdplbBytes []byte
